server:
  port: 8090
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/marcustrng/uth-management-system.git
          search-paths: configuration
          default-label: main
