INSERT INTO career_levels (career_level_name)
VALUES ('Undergraduate'),
       ('Graduate'),
       ('PhD');

INSERT INTO departments (department_name)
VALUES ('Science'),
       ('Literature'),
       ('Engineering');

INSERT INTO careers (career_name, department_id, duration_years, required_optional_courses,
                     career_level_id)
VALUES ('Mechanical Engineering', 3, 4, 4, 1),
       ('Psychology', 2, 5, 6, 1),
       ('Computer Science', 1, 4, 3, 2),
       ('Chemistry', 1, 3, 2, 2);

INSERT INTO courses (course_name, course_code, career_id, year, semester, optional)
VALUES ('Mathematics 1', 'MAT-1', 1, 1, 1, false),
       ('Mathematics 2', 'MAT-2', 1, 2, 1, false),
       ('Physics 1', 'PHY-1', 1, 1, 2, false),
       ('Physics 2', 'PHY-2', 1, 2, 2, false),
       ('Introduction to Psychology', 'PSY-1', 2, 1, 1, false),
       ('Advanced Psychology', 'PSY-2', 2, 2, 1, false),
       ('Computer Programming', 'CSC-1', 3, 1, 1, false),
       ('Database Management', 'CSC-2', 3, 2, 1, false),
       ('Organic Chemistry', 'CHM-1', 4, 1, 1, false),
       ('Inorganic Chemistry', 'CHM-2', 4, 2, 1, false),
       ('Literature 1', 'LIT-1', 2, 1, 1, false),
       ('Literature 2', 'LIT-2', 2, 2, 1, false),
       ('Mechanics', 'MEC-1', 1, 3, 1, false),
       ('Thermodynamics', 'MEC-2', 1, 4, 1, false),
       ('Database Design', 'CSC-3', 3, 3, 1, false),
       ('Web Development', 'CSC-4', 3, 4, 1, false),
       ('Analytical Chemistry', 'CHM-3', 4, 3, 1, false),
       ('Physical Chemistry', 'CHM-4', 4, 4, 1, false),
       ('Introduction to Biology', 'BIO-101', 1, 1, 1, false),
       ('Cell Biology', 'BIO-201', 1, 2, 1, false),
       ('Genetics', 'BIO-301', 1, 3, 1, false),
       ('Molecular Biology', 'BIO-401', 1, 4, 1, false),
       ('English Literature', 'LIT-101', 2, 1, 1, false),
       ('World Literature', 'LIT-201', 2, 2, 1, false),
       ('American Literature', 'LIT-301', 2, 3, 1, false),
       ('Shakespearean Literature', 'LIT-401', 2, 4, 1, false),
       ('Introduction to Computer Science', 'CSC-101', 3, 1, 1, false),
       ('Data Structures and Algorithms', 'CSC-201', 3, 2, 1, false),
       ('Operating Systems', 'CSC-301', 3, 3, 1, false),
       ('Artificial Intelligence', 'CSC-401', 3, 4, 1, false),
       ('Organic Chemistry 1', 'CHM-101', 4, 1, 1, false),
       ('Inorganic Chemistry 1', 'CHM-201', 4, 2, 1, false),
       ('Analytical Chemistry', 'CHM-301', 4, 3, 1, false),
       ('Physical Chemistry', 'CHM-401', 4, 4, 1, false),
       ('Introduction to Economics', 'ECO-101', 1, 1, 1, false),
       ('Microeconomics', 'ECO-201', 1, 2, 1, false),
       ('Macroeconomics', 'ECO-301', 1, 3, 1, false),
       ('International Economics', 'ECO-401', 1, 4, 1, false),
       ('Creative Writing', 'LIT-101', 2, 1, 1, false),
       ('Poetry Writing', 'LIT-201', 2, 2, 1, false),
       ('Fiction Writing', 'LIT-301', 2, 3, 1, false),
       ('Playwriting', 'LIT-401', 2, 4, 1, false),
       ('Introduction to Computer Programming', 'CSC-101', 3, 1, 1, false),
       ('Data Structures', 'CSC-201', 3, 2, 1, false),
       ('Software Engineering', 'CSC-301', 3, 3, 1, false),
       ('Machine Learning', 'CSC-401', 3, 4, 1, false),
       ('Organic Chemistry 1', 'CHM-101', 4, 1, 1, false),
       ('Inorganic Chemistry 1', 'CHM-201', 4, 2, 1, false),
       ('Biochemistry', 'CHM-301', 4, 3, 1, false),
       ('Physical Chemistry', 'CHM-401', 4, 4, 1, false);

INSERT INTO course_dependency (course_id, required_course_id)
VALUES (1, 2),
       (3, 4),
       (5, 6),
       (7, 8),
       (9, 10),
       (11, 12),
       (13, 14),
       (15, 16),
       (2, 3),
       (4, 5),
       (6, 7),
       (8, 9),
       (10, 11),
       (12, 13),
       (14, 15);

INSERT INTO professors (first_name, last_name, email, phone_number)
VALUES ('John', 'Smith', 'john.smith@example.com', '123-456-7890'),
       ('Emily', 'Johnson', 'emily.johnson@example.com', '987-654-3210'),
       ('Michael', 'Williams', 'michael.williams@example.com', '555-555-5555'),
       ('Jessica', 'Brown', 'jessica.brown@example.com', '111-222-3333'),
       ('David', 'Jones', 'david.jones@example.com', '444-444-4444'),
       ('Jennifer', 'Miller', 'jennifer.miller@example.com', '999-888-7777'),
       ('Daniel', 'Lee', 'daniel.lee@example.com', '111-222-3333'),
       ('Michelle', 'Wong', 'michelle.wong@example.com', '444-555-6666'),
       ('Christopher', 'Nguyen', 'christopher.nguyen@example.com', '777-888-9999'),
       ('Stephanie', 'Garcia', 'stephanie.garcia@example.com', '123-456-7890'),
       ('Ryan', 'Martinez', 'ryan.martinez@example.com', '987-654-3210'),
       ('Alexandra', 'Davis', 'alexandra.davis@example.com', '555-111-2222'),
       ('Matthew', 'Wilson', 'matthew.wilson@example.com', '777-888-9999'),
       ('Sophia', 'Brown', 'sophia.brown@example.com', '333-444-5555'),
       ('Benjamin', 'Lopez', 'benjamin.lopez@example.com', '888-999-0000'),
       ('Olivia', 'Garcia', 'olivia.garcia@example.com', '111-222-3333');

INSERT INTO professor_course (professor_id, course_id)
VALUES
    (1, 1),
    (1, 2),
    (2, 3),
    (3, 1),
    (3, 4),
    (4, 2),
    (5, 3),
    (5, 4),
    (6, 1);
