spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/year_planning
    spring.datasource.driver-class-name: org.postgresql.Driver
    username: keycloak
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  ## API SECURITY WITH KEYCLOAK PROVIDER
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9300/realms/uth-oidc-dev
jwt:
  auth:
    converter:
      resource-id: uth-client
      principal-attribute: preferred_username

flyway:
  url: ${spring.datasource.url}

server:
  port: 8094

app:
  cors:
    allowed-origins: http://localhost:3000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

info:
  app:
    name: ${spring.application.name}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

