spring:
  ## GATEWAY CONFIGURATIONS
  cloud:
    gateway:
      routes:
        ## CAREER SERVICE
        - id: ums-service-career
          uri: lb://ums-service-career
          predicates:
            - Path=/ums-service-career/**
          filters:
            - StripPrefix=1
        ## STUDENT SERVICE
        - id: ums-service-enrollment
          uri: lb://ums-service-enrollment
          predicates:
            - Path=/ums-service-enrollment/**
          filters:
            - StripPrefix=1
        ## PLANNING SERVICE
        - id: ums-service-schedule
          uri: lb://ums-service-schedule
          predicates:
            - Path=/ums-service-schedule/**
          filters:
            - StripPrefix=1
        ## KEYCLOAK CONNECTOR
        - id: ums-connector-keycloak
          uri: lb://ums-connector-keycloak
          predicates:
            - Path=/ums-connector-keycloak/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9300/realms/uth-oidc-dev
  jwt:
    auth:
      converter:
        resource-id: uth-client
        principal-attribute: preferred_username

server:
  port: 8080

app:
  cors:
    allowed-origins: http://localhost:3000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
