spring:
  ## GATEWAY CONFIGURATIONS
  cloud:
    gateway:
      routes:
        ## CAREER SERVICE
        - id: ums-service-career
          uri: lb://ums-service-career
          predicates:
            - Path=/careers/**
          filters:
            - StripPrefix=1
        ## STUDENT SERVICE
        - id: ums-service-enrollment
          uri: lb://ums-service-enrollment
          predicates:
            - Path=/students/**
          filters:
            - StripPrefix=1

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
